name: gorgon
version: 0.13.5
author: Cantidio Oliveira Fontes <aniquilatorbloody@gmail.com>
description: Have you ever wanted to create 2D games to be played in your browser, but stuck with crazy canvas and WebGL functions? Now you can create your 2D Games without caring about canvas or other html5 technologies. Gorgon is a simple game development library, which you can create your own 2D games in a fast and easy way.
homepage: https://github.com/cantidio/gorgonDart
environment:
  sdk: '>=1.5.2'
dependencies:
  async: '>=1.0.0 <2.0.0'
  browser: '>=0.10.0+2 <0.11.0'
dev_dependencies:
  unittest: '>=0.11.0+2 <0.12.0'
